# Generated by Django 5.0.7 on 2024-07-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
            ],
        ),
    ]
