# Generated by Django 5.0.7 on 2024-08-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packngoapp', '0002_order_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=200)),
                ('order_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('pickup_loc', models.IntegerField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')])),
                ('drop_loc', models.IntegerField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')])),
                ('delivery_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('contact_info', models.IntegerField()),
                ('vehicle_info', models.CharField(max_length=200)),
                ('availability_status', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('image', models.ImageField(upload_to='reviewimage')),
            ],
        ),
    ]
