# Generated by Django 5.0.7 on 2024-08-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packngoapp', '0003_delivery_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='book',
        ),
    ]
