# Generated by Django 5.0.7 on 2024-08-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packngoapp', '0004_rename_order_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('payment_info', models.CharField(max_length=200)),
                ('pickup_loc', models.IntegerField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')])),
                ('drop_loc', models.IntegerField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')])),
                ('phone_no', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
