# Generated by Django 5.0.7 on 2024-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packngoapp', '0005_books_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='drop_loc',
            field=models.CharField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')], max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='pickup_loc',
            field=models.CharField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')], max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='drop_loc',
            field=models.CharField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')], max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_loc',
            field=models.CharField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')], max_length=200),
        ),
    ]
