# Generated by Django 5.0.7 on 2024-08-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packngoapp', '0006_alter_books_drop_loc_alter_books_pickup_loc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pickup_loc', models.CharField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')], max_length=200)),
                ('drop_loc', models.CharField(choices=[('pune', 'pune'), ('mumbai', 'mumbai'), ('agra', 'agra'), ('beed', 'beed'), ('solapur', 'solapur'), ('banglore', 'banglore'), ('delhi', 'delhi'), ('mirzapur', 'mirzapur'), ('jaunpur', 'jaunpur')], max_length=200)),
                ('phone_no', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='books',
        ),
    ]
