# Generated by Django 5.0.7 on 2024-08-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packngoapp', '0007_booking_delete_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='delivery',
        ),
        migrations.DeleteModel(
            name='driver',
        ),
    ]
