# Generated by Django 5.0.7 on 2024-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packngoapp', '0008_delete_delivery_delete_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(choices=[('0-20', '0-20'), ('20-40', '20-40'), ('40-60', '40-60')]),
        ),
    ]
