# Generated by Django 5.0.7 on 2024-08-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packngoapp', '0009_alter_booking_price_alter_booking_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.CharField(choices=[('0-20', '0-20'), ('20-40', '20-40'), ('40-60', '40-60')], max_length=200),
        ),
    ]
