# Generated by Django 5.0.7 on 2024-08-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packngoapp', '0010_alter_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
